### ISSUE TITLE
Allow imports to match an ID via other, more practical attribute types.

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/sprout-import#25]
This is my major pain point, the big one here is `folderId`. It would be great to get some "helpers" that do the ID lookup for me. Suggestions in parenthesis.

- `attributes.authorId` (authorUsername)
- `attributes.typeId` (typeHandle)
- `attributes.sectionId` (sectionHandle)
- `matchCriteria.folderId` (folderPath)
- `matchCriteria.volumeId` (volumeHandle)
- `matchCriteria.groupId` (groupHandle)

### Notify

- [x] [6527399737](https://app.intercom.io/a/apps/dfa024eb83c11784227312bba407fb3d35e00fa7/inbox/inbox/conversation/6527399737)

**Comment by BenParizek** [comment]
We'll look into adding support for this.

In the meantime, the best place to address this is likely during the export stage of the migration process by adding a mapping to swap in the ID you need for the new database.

**Comment by BenParizek** [comment]
@colinmeinke This has been improved in the latest release.

We now support matching several of these attributes via a new [Related Attributes](https://sprout.barrelstrengthdesign.com/docs/import/related-attributes.html) feature.

attributes.authorId (authorUsername)
attributes.typeId (typeHandle)
attributes.sectionId (sectionHandle)

We'll look into extending this to more items next:

- matchCriteria.folderId (folderPath)
- matchCriteria.volumeId (volumeHandle)
- matchCriteria.groupId (groupHandle)
