### ISSUE TITLE
Feature Request: Better Error Handling When Import Fails

### ISSUE THREAD

**Issue by kmgdevelopment** [barrelstrength/sprout-import#75]
I'd like to see better error handling when an import fails for whatever reason. For example, if you forget to include the `typeId` parameter, or if you misspell the name of a field. 

Currently the import runs and silently fails - no new entry is created yet there are no errors to explain why the entry wasn't created. Or an entry is created but a field is not populated and there are no errors to explain why.

**Comment by kgrote** [comment]
Also imports will fail silently if the field being imported exceeds the character limit of the Craft field.

**Comment by BenParizek** [comment]
Thanks for the feedback, Kristen. We'll review each of these ideas and integrate what we can when we have a chance. In some scenarios it gets a bit tricky, but we do try to log errors where we can and would be happy to make these issues easier to diagnose if we can do so.
